version: "3"
services:
  server:
    image: pabloa009/api-pra2
    command: npm start
    volumes:
      - ./server:/api/src/app
    ports:
      - "5000:5000"
  client:
    image: pabloa009/frontend-pra2
    command: npm start
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"